"""added active to stops

Revision ID: 00caa4801eab
Revises: e53a77b7d2ef
Create Date: 2018-02-08 17:08:33.893148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00caa4801eab'
down_revision = 'e53a77b7d2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stop', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stop', 'active')
    # ### end Alembic commands ###
