"""added in addresses

Revision ID: 1f577deca0c0
Revises: bbcaab4cef4c
Create Date: 2018-02-06 12:17:28.851416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f577deca0c0'
down_revision = 'bbcaab4cef4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('street_address', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_city'), 'address', ['city'], unique=False)
    op.create_index(op.f('ix_address_timestamp'), 'address', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_timestamp'), table_name='address')
    op.drop_index(op.f('ix_address_city'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
