"""created a address stops model

Revision ID: 348644bb983f
Revises: f0b4712c5e3a
Create Date: 2018-02-25 18:00:44.814283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348644bb983f'
down_revision = 'f0b4712c5e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_stops', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_stops', 'active')
    # ### end Alembic commands ###
