"""added latitude and longitude to addresses

Revision ID: 83c9db999891
Revises: 1f577deca0c0
Create Date: 2018-02-06 12:22:32.990534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c9db999891'
down_revision = '1f577deca0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('address', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'longitude')
    op.drop_column('address', 'latitude')
    # ### end Alembic commands ###
