"""updating stops tbl and relationships

Revision ID: 95cbc17d9502
Revises: 00caa4801eab
Create Date: 2018-02-13 14:31:29.411290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cbc17d9502'
down_revision = '00caa4801eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_stops',
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], )
    )
    op.add_column('stop', sa.Column('address', sa.String(length=512), nullable=True))
    op.add_column('stop', sa.Column('direction', sa.String(length=128), nullable=True))
    op.add_column('stop', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('stop', sa.Column('longitude', sa.Float(), nullable=False))
    op.drop_constraint('stop_user_id_fkey', 'stop', type_='foreignkey')
    op.drop_column('stop', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stop', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('stop_user_id_fkey', 'stop', 'user', ['user_id'], ['id'])
    op.drop_column('stop', 'longitude')
    op.drop_column('stop', 'latitude')
    op.drop_column('stop', 'direction')
    op.drop_column('stop', 'address')
    op.drop_table('address_stops')
    # ### end Alembic commands ###
