"""added uniqueness to stop_id

Revision ID: b112caaac731
Revises: 95cbc17d9502
Create Date: 2018-02-13 15:29:04.537812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b112caaac731'
down_revision = '95cbc17d9502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stop', ['stop_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop', type_='unique')
    # ### end Alembic commands ###
