"""updating address data types

Revision ID: e53a77b7d2ef
Revises: 83c9db999891
Create Date: 2018-02-06 16:06:17.150370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53a77b7d2ef'
down_revision = '83c9db999891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('address', sa.Column('zip_code', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'zip_code')
    op.drop_column('address', 'state')
    # ### end Alembic commands ###
