"""changed pk for lat long to indexes

Revision ID: f0b4712c5e3a
Revises: 360a6a3e1d83
Create Date: 2018-02-25 17:51:04.143900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0b4712c5e3a'
down_revision = '360a6a3e1d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('address', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_address_latitude'), 'address', ['latitude'], unique=False)
    op.create_index(op.f('ix_address_longitude'), 'address', ['longitude'], unique=False)
    op.alter_column('stop', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stop', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_stop_latitude'), 'stop', ['latitude'], unique=False)
    op.create_index(op.f('ix_stop_longitude'), 'stop', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stop_longitude'), table_name='stop')
    op.drop_index(op.f('ix_stop_latitude'), table_name='stop')
    op.alter_column('stop', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stop', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_address_longitude'), table_name='address')
    op.drop_index(op.f('ix_address_latitude'), table_name='address')
    op.alter_column('address', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('address', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
